//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMVC_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class actividades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public actividades()
        {
            this.colaborador = new HashSet<colaborador>();
        }
    
        public int ID_actividad { get; set; }
        public string actividad { get; set; }
        public Nullable<System.DateTime> fecha_asignacion { get; set; }
        public Nullable<System.DateTime> fecha_finalizacion { get; set; }
        public Nullable<int> tiempo_horas { get; set; }
        public Nullable<int> tiempo_dias { get; set; }
        public Nullable<int> tiempo_minutos { get; set; }
        public int actividades_cliente { get; set; }
        public int actividades_estado { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual estado_actividad estado_actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<colaborador> colaborador { get; set; }
    }
}
