//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMVC_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class control_colaborador
    {
        public int ID_control { get; set; }
        public string tiempo_horas_semana { get; set; }
        public string tiempo_horas_mes { get; set; }
        public int control_colaborador1 { get; set; }
    
        public virtual colaborador colaborador { get; set; }
    }
}
