//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMVC_Demo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NexusWorkHoursSEntities1 : DbContext
    {
        public NexusWorkHoursSEntities1()
            : base("name=NexusWorkHoursSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actividades> actividades { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<colaborador> colaborador { get; set; }
        public virtual DbSet<control_colaborador> control_colaborador { get; set; }
        public virtual DbSet<estado_actividad> estado_actividad { get; set; }
        public virtual DbSet<proyectos> proyectos { get; set; }
        public virtual DbSet<proyectos> login { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
